### ISSUE TITLE
Can't resolve 'hipay-fullservice-sdk-js'

### ISSUE THREAD

**Issue by antonkri97** [hipay/hipay-fullservice-sdk-js#35]
Hi! I've installed [hipay fullservice sdk](https://www.npmjs.com/package/hipay-fullservice-sdk-js) from npm.  And I've tried to import HiPay just like that
```
import HiPay from "hipay-fullservice-sdk-js";
```
But Webpack can't resolve **hipay-fullservice-sdk-js**  package

**Comment by aymericfc** [comment]
Hello @antonkri97, you can see the documentation to install this SDK here : https://developer.hipay.com/doc/hipay-enterprise-sdk-js_2/#installation-using-npm

Please let us know if you where able to install it.

**Comment by antonkri97** [comment]
Hello, this documentation does not cover modern SPA. My project is based on ES Modules and I still not fully understand how to import your package. When using default imports, there is an error: Module not found: Can't resolve 'hipay-fullservice-sdk-js’.

**Comment by antonkri97** [comment]
Maybe it is better to move our dialog to my Github issue?

**Comment by FlorianBurgevin** [comment]
Hello @antonkri97,

The SDK is not compatible with ES Modules nor CommonJS yet.
You need to include it directly in the head of your index.html file as a script.

If you installed it via npm or yarn, you should link to "hipay-fullservice-sdk-js/dist/hipay-fullservice-sdk-2.min.js"
