### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Ctaque** [hipay/hipay-fullservice-sdk-js#36]
We use typescript in our project. The javascript sdk is not compatible with typescript. There is no typings file in the project root neither in definitly typed  [repository](https://github.com/DefinitelyTyped/DefinitelyTyped)

I tried generating one with [dts-gen ](https://github.com/Microsoft/dts-gen) and I got this error : 

> Couldn't load module "hipay-fullservice-sdk-js". Please install it globally (npm install -g hipay-fullservice-sdk-js) and try again.

Which i did and got the same error.

As a side way question, what is the vanilia alternative to hipay-fullservice-sdk-js?

**Comment by FlorianBurgevin** [comment]
Hello,

The sdk is not compatible with ES6 Modules. So, you can't import or require it.

I think dts-gen try to import the library to generate some files?

**Comment by Ctaque** [comment]
Hello,
I don't know how dts-gen works, so I managed to load the library with a script tag.
