### ISSUE TITLE
[BUG] SDK V3 broken on IE11

### ISSUE THREAD

**Issue by odusseys** [hipay/hipay-fullservice-sdk-js#40]
SDK version: hipay-enterprise-sdk-js_3 (through https://libs.hipay.com/js/sdkjs.js)
Browser: IE11 (through Browserstack)
The `cardInstance` initialization fails with a `TypeError: Object expected`, culprit seems to be `_checkAndSanitizeFields`

Code used is the following:
```
const HIPAY_CONFIG = {
  fields: {
    cardHolder: {
      selector: 'hipay-card-holder',
    },
    cardNumber: {
      selector: 'hipay-card-number',
    },
    expiryDate: {
      selector: 'hipay-expiry-date',
    },
    cvc: {
      selector: 'hipay-cvc',
      helpButton: true,
    },
  },
  styles: {
    base: {
      color: '#1c005a',
    },
  },
};

// all constants here are correctly initialized to strings
const hipay = window.HiPay({
        username: HIPAY_PUBLIC_USERNAME,
        password: HIPAY_PUBLIC_PASSWORD,
        environment: HIPAY_ENV,
        lang: locale,
      });
const cardInstance = hipay.create('card', HIPAY_CONFIG);  // throws

```

**Comment by FlorianBurgevin** [comment]
Hello @odusseys 

I couldn't be able to reproduce your problem.
Here is a jsFiddle with your code and it works for me.

https://jsfiddle.net/zkxnvs7g/6/

**Comment by odusseys** [comment]
Indeed, strange, may be an issue with conflicting polyfills in our build chain. Will look into it on my side, I guess you can ignore this issue - apologies.

**Comment by FlorianBurgevin** [comment]
No worries, 
Let us know if you have any problem.
